export const routeOptions = [
    "Uso oral",
    "Uso oral contínuo",
    "Uso Tópico",
    "Uso Externo",
    "Uso Nasal",
    "Uso Vaginal",
    "Uso Retal",
    "Uso Subcutâneo",
    "Uso Intramuscular",
    "Uso Intravenoso",
    "Uso Oftálmico",
    "Uso Otológico",
    "Uso Inalatório",
    "Nebulização",
    "Declaração",
    "Relatório",
    "Laudo Médico",
    "Orientações",
    "Encaminhamento",
    "Retorno",
    "Atestado",
    "Solicitação de exames",
];